// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBUH63xqDARs_51SNOUV-Fyio58N1uWA',
    appId: '1:783157217398:web:6f5beebb970735711f7757',
    messagingSenderId: '783157217398',
    projectId: 'employee-management-86c85',
    authDomain: 'employee-management-86c85.firebaseapp.com',
    storageBucket: 'employee-management-86c85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoqGvewdPcIfqo3lvmtUanokGLxb3tuo',
    appId: '1:783157217398:android:58d475fd95de397c1f7757',
    messagingSenderId: '783157217398',
    projectId: 'employee-management-86c85',
    storageBucket: 'employee-management-86c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHiNZvDFLdN-LCTgVgupixZcrUj4UWocI',
    appId: '1:783157217398:ios:c2e8d8df89bf24761f7757',
    messagingSenderId: '783157217398',
    projectId: 'employee-management-86c85',
    storageBucket: 'employee-management-86c85.appspot.com',
    iosBundleId: 'com.employeemanagement.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHiNZvDFLdN-LCTgVgupixZcrUj4UWocI',
    appId: '1:783157217398:ios:c2e8d8df89bf24761f7757',
    messagingSenderId: '783157217398',
    projectId: 'employee-management-86c85',
    storageBucket: 'employee-management-86c85.appspot.com',
    iosBundleId: 'com.employeemanagement.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMBUH63xqDARs_51SNOUV-Fyio58N1uWA',
    appId: '1:783157217398:web:db8a21c83f0333c81f7757',
    messagingSenderId: '783157217398',
    projectId: 'employee-management-86c85',
    authDomain: 'employee-management-86c85.firebaseapp.com',
    storageBucket: 'employee-management-86c85.appspot.com',
  );
}
